name: CI

on:
  pull_request:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # remove macos temporarily
        os: [ubuntu-latest, windows-latest]
        node_version: [24]
      fail-fast: false

    name: 'Build&Test: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Get pnpm store directory
        id: pnpm-store
        shell: bash
        run: echo "path=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm modules
        uses: actions/cache@v5
        with:
          path: ${{ steps.pnpm-store.outputs.path }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Install Playwright Chromium
        run: pnpm exec playwright install chromium

      - name: Build vite-plugin-federation
        run: pnpm run build

      - name: Unit test
        run: pnpm run 'test:unit'

      - name: Dev mode e2e test
        run: pnpm run 'test:e2e-dev'
        timeout-minutes: 5

      - name: Serve mode e2e test
        run: pnpm run 'test:e2e-serve'
        timeout-minutes: 5

  lint:
    runs-on: ubuntu-latest
    name: 'Lint: node-24, ubuntu-latest'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Set node version to 24
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Prepare
        run: pnpm run build
      - name: Lint
        run: pnpm run lint
